
org.quartz.scheduler.instanceName = MyScheduler
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.dataSource = echoes
org.quartz.jobStore.tablePrefix = qrtz_
org.quartz.jobStore.isClustered = true

org.quartz.dataSource.echoes.driver = org.postgresql.Driver
org.quartz.dataSource.echoes.URL = jdbc:postgresql://localhost:5432/echoes
org.quartz.dataSource.echoes.user = echoes
org.quartz.dataSource.echoes.password = echoes
org.quartz.job-store-type=jdbc
org.quartz.jdbc.initialize-schema=never
org.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.properties.org.quartz.jobStore.isClustered=false